accounts/urls.py
from django.urls import path
from .views import register_view, UserDetailView, UserChangeView, UserChangePasswordView,logout_view,login_view

app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('create/', register_view, name='create'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import FileListView, FileDeleteView, FileUpdateView, FileDetailView, FileCreateView

urlpatterns = [
    path('', FileListView.as_view(), name='index'),
    path('create/', FileCreateView.as_view(), name='create'),
    path('detail/<int:pk>', FileDetailView.as_view(), name='detail'),
    path('update/<int:pk>', FileUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', FileDeleteView.as_view(), name='delete')
    ]

app_name = 'webapp'

webapp/models.py
from django.contrib.auth.models import User
from django.db import models


ACCESS_CHOICES = [
    ('shared', 'общий'),
    ('secured', 'скрытый'),
    ('private', 'приватный')
]

class File(models.Model):
    file = models.FileField(upload_to='uploads/files',null=False,blank=False,
                                verbose_name='File')
    name = models.CharField(max_length=1000, null=False, blank=False, verbose_name='Description')
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='file_author',
                               null=True, blank=True, verbose_name='Author')
    access = models.CharField(max_length=25,choices=ACCESS_CHOICES, default=ACCESS_CHOICES[0][0], verbose_name='Access',
                            null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation date')

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return self.name

webapp/forms.py
from django import forms

from webapp.models import File


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['author', 'created_at', 'access']


class AuthFileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at','author']

class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

webapp/views.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.utils.http import urlencode
from webapp.forms import FileForm, SimpleSearchForm, AuthFileForm
from webapp.models import File


class FileListView(ListView):

    model = File
    template_name = 'list.html'
    context_object_name = 'files'
    ordering = ['-created_at']
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(access='shared')
        if self.search_value:
            queryset = queryset.filter(
                Q(name__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SimpleSearchForm(data=self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class FileDetailView(DetailView):

    model = File
    template_name = 'detail.html'
    context_object_name = 'file'


class FileCreateView(CreateView):

    model = File
    form_class = FileForm
    template_name = 'create.html'

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return AuthFileForm
        return FileForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
        if not self.request.user.is_authenticated:
            form.instance.author = None
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:detail', kwargs={'pk': self.object.pk})


class FileUpdateView(UpdateView):

    model = File
    form_class = FileForm
    context_object_name = 'file'
    template_name = 'update.html'

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author:
            return super().dispatch(request, *args, **kwargs)
        if not request.user.has_perm('webapp.change_file'):
            raise PermissionDenied('403 Forbidden')
        return super().dispatch(request, *args, **kwargs)


class FileDeleteView(DeleteView):

    model = File
    template_name = 'delete.html'
    success_url = reverse_lazy('webapp:index')

    def get_object(self, queryset=None):
        file = File.objects.get(pk=self.kwargs.get('pk'))
        return file

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if self.request.user == file.author:
            return super().dispatch(request, *args, **kwargs)
        if not request.user.has_perm('webapp.delete_file'):
            raise PermissionDenied('403 Forbidden')
        return super().dispatch(request, *args, **kwargs)

webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Issue-Tracker{% endblock %}</title>
    {% block styles %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="#">
        <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light bg-secondary align-items-start">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav w-100">
                    <li class="nav-item">
                        <a href="{% url 'webapp:index' %}" class="nav-link">Домой</a>
                    </li>
                    <li>
                        <a href="{% url 'webapp:create' %}" class="nav-link">Создать</a>
                    </li>
                {% if user.is_authenticated %}
                {% block menu_links %}{% endblock %}
                <li class="menu-right">
                    <a href="{% url 'accounts:logout' %}" class="nav-link">
                        Выход
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:user_detail' request.user.pk %}" class="nav-link">
                        Привет, {{ request.user }}!
                    </a>
                </li>
            {% else %}
                <li class="menu-right">
                    <a href="{% url 'accounts:login' %}" class="nav-link">
                        Вход
                    </a>
                </li>
                <li class="menu-right">
                    <a href="{% url 'accounts:create' %}" class="nav-link">
                        Регистрация
                    </a>
                </li>
                <li>
            </li>
            {% endif %}
                    {% block menu %}{% endblock %}
                </ul>
            </div>
        </nav>
            {% block content %}{% endblock %}
        </div>

        <script src="{% static 'js/main.js' %}"></script>
        {% block scripts %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/create.html
{% extends 'base.html' %}
{% block title %}Create announce{% endblock %}
{% block content %}
   <h1>Create Task</h1>
        <form method="POST" action="{% url "webapp:create" %}" enctype="multipart/form-data">
            {% csrf_token %}
                {% include 'partial/form.html' with button_text="Create" %}
        </form>
{% endblock %}

webapp/templates/delete.html
{% extends 'base.html' %}
{% block title %}Delete file{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Вы уверены что хотите удалить файл?</h1>
        <form method="POST" action="{% url 'webapp:delete' file.pk %}" class="text-center">
            {% csrf_token %}
            <p><input type="submit" class = 'btn btn-secondary' value="Подтвердить"></p>
            <p><a href="{% url 'webapp:index'  %}" class = 'btn btn-secondary'>Отмена</a></p>
        </form>
{% endblock %}

webapp/templates/detail.html
{% extends 'base.html' %}
{% block menu %}
    {% if perms.webapp.change_file %}
        <li class="nav-item">
            <a href="{% url 'webapp:update' file.pk %}" class="nav-link">Обновить</a>
        </li>
    {% elif request.user == file.author %}
        <li class="nav-item">
            <a href="{% url 'webapp:update' file.pk %}" class="nav-link">Обновить</a>
        </li>
    {% endif %}
    {% if perms.webapp.delete_file %}
        <li>
            <a href="{% url 'webapp:delete' file.pk %}" class="nav-link">Удалить</a>
        </li>
    {% elif request.user == file.author %}
        <li>
            <a href="{% url 'webapp:delete' file.pk %}" class="nav-link">Удалить</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    {% if file.author %}
        <h5><a href="{% url "accounts:user_detail" file.author.pk %}">Добавил: {{ file.author }}</a></h5>
    {% else %}
        <h5>Добавил: Аноним</h5>
    {% endif %}
    <p><a href="{{ file.file.url }}" download >Загрузить файл</a></p>
    <p>{{ file.name }}</p>
    <p>  Загружен:   {{ file.created_at }}</p>
    <p> Доступ: {{ file.access }}</p>
{% endblock %}

webapp/templates/list.html
{% extends 'base.html' %}
{% load i18n %}
{% block menu %}
    <div class="search col-md-8" >
        {% include 'partial/simple_search.html' %}
    </div>
{% endblock %}
{% block title %}Список файлов{% endblock %}
{% block content %}
    <h1 class="text-center mb-5">Список файлов</h1>
    <div class="row">
        {% for file in files %}
                <div class="col-md-12 mt-5 mb-5 border border-primary" id="product-{{ file.pk }}" >
                    <h5 class="card-header"><a href="{% url "webapp:detail" file.pk %}"
                           class="btn bg-secondary">{{ file.name }}</a></h5>
                    {% if file.author %}
                        <p class="card-body">
                            <a href="{% url 'accounts:user_detail' file.author.pk%}">
                                Добавил: {{ file.author }}
                            </a>
                    {% else %}
                        </p>
                        <p class="card-body">{% blocktrans %}Добавил: Аноним {% endblocktrans %}</p>
                    {% endif %}
                        <p><a href="{{ file.file.url }}" download >Загрузить файл</a></p>
                        <p>Загружен: {{ file.created_at }}</p>
                        <p> Доступ к файлу: {{ file.access }}</p>
                </div>
            </div>
        {% endfor %}
    {% if is_paginated %}
            {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

webapp/templates/update.html
{% extends 'base.html' %}
{% block title %}Редактировать{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <h1>Изменить</h1>
        <form method="POST" action="{% url 'webapp:update' file.pk %}">
            {% include 'partial/form.html' with button_text="Update" %}
        </form>
{% endblock %}